# Generated by Django 4.1 on 2022-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleKPoblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPoblacion', models.IntegerField()),
                ('idKmeans', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kmeansOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitudes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='poblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitudes', models.TextField()),
                ('latitudes', models.TextField()),
            ],
        ),
    ]
