# Generated by Django 4.1 on 2022-10-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_modelosKmeans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmeansopciones',
            name='longitudes',
        ),
        migrations.AddField(
            model_name='kmeansopciones',
            name='clusters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kmeansopciones',
            name='iteraciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kmeansopciones',
            name='tolerancia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
