# Generated by Django 4.1 on 2022-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0003_modelosKmeans'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeansopciones',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
