# Generated by Django 4.1 on 2022-12-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0004_AlterarModelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmeansEncuestaOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusters', models.IntegerField()),
                ('tolerancia', models.FloatField()),
                ('iteraciones', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
    ]
