# Generated by Django 4.1 on 2022-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0005_kmeansencuestaopciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='svmoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.BooleanField()),
                ('stream', models.BooleanField()),
                ('club', models.BooleanField()),
                ('gasto', models.BooleanField()),
            ],
        ),
    ]
